### ISSUE TITLE
multiple selection without shift

### ISSUE THREAD

**Issue by martinleopold** [thomasgriffin/New-Media-Image-Uploader#10]
Also, not a bug, but still kind of an issue. Is there a way to allow for multiple selections _without_ the need to press shift? (Just like when creating a "gallery" in the new uploader). For me it makes more sense, when allowing multiple images in the first place, to make it as easy as possible for users, thus not require a special key to really select multiple images. Any advice much appreciated.

**Comment by thomasgriffin** [comment]
I haven't done anything special in this regard, so any updates to this will be made in core (and thus pulled over to this script).
