### ISSUE TITLE
Adding support for multiple fields.

### ISSUE THREAD

**Issue by AnghelGabriel** [thomasgriffin/New-Media-Image-Uploader#4]
Let's say we have a custom metabox. Where we have only one button "Upload media".
Is there a posibility after selecting more then one images to create the html with something like attachment.each() ?

I'm trying to do this but did't found a way yet.

Best Regards.
Anghel Gabriel

EDIT:
Nevermind i found i way.

**Comment by thomasgriffin** [comment]
Closing since you found a way. :-)
