### ISSUE TITLE
library type?

### ISSUE THREAD

**Issue by turtlepod** [thomasgriffin/New-Media-Image-Uploader#7]
hi thomas, another question.
in media.js there's 

``` javascript
library: {
    type: 'image'
},
```

is there a list of available type?
how to add more than one library type?
how about file extension? for example i just want to list zip file?
can i also have more than one file ext? for example zip and pdf?

thank you

**Comment by bainternet** [comment]
I'd asked the same question myself until I tested it, So:

**is there a list of available type?**

All defined mime_types e.g:

``` JS
library: {
    type: 'pdf'
},
```

Which you can add to WordPress using `upload_mimes` filter hook e.g:

``` php
add_filter( 'upload_mimes', 'add_mimes' );
function add_mimes( $mime_types ) {

        $mime_types['pdf'] = 'application/pdf';
        $mime_types['doc|docx'] = 'application/msword';

        return $mime_types;
}
```

and to have more then one you just name them in an array e.g:

``` JS
library: {
    type: ['pdf','doc','docx']
},
```

**Comment by turtlepod** [comment]
thank you very much bainternet.
i was testing it with `wp_check_filetype` your filter seems to be working fine.
http://codex.wordpress.org/Function_Reference/wp_check_filetype

i'm not really sure, but when i test the library with 

``` javascript
library: {
    type: 'zip'
},
```

it also working (?)

**Comment by bainternet** [comment]
actually you need to use the mime type value ex:

``` JS
library: {
    type: 'application/pdf'
},
```

Or for zip files :

``` JS
library: {
    type: 'application/zip'
},
```

other then that you can also use `'image','audio','video','file'`
