### ISSUE TITLE
media.attachment data?

### ISSUE THREAD

**Issue by turtlepod** [thomasgriffin/New-Media-Image-Uploader#8]
hi again.
in this example plugin you use `media_attachment.url` to get url of the image url.
https://github.com/thomasgriffin/New-Media-Image-Uploader/blob/master/js/media.js#L133

is there another data i can use, for example attachment id, or maybe file size, image width, height etc.
how do i var_dump this data?

thank you.

**Comment by dameian** [comment]
Go to media.js line 133 and change this...

$('#tgm-new-media-image').val(media_attachment.url);

to...

$('#tgm-new-media-image').val(media_attachment.id);

That will give you the attachment ID :)

You can add this line directly above line 133...

console.log(media_attachment);

and see the other items available for usage in your browser console as well. 

Hope this helps!

**Comment by turtlepod** [comment]
thak you... i'll test it soon ;)

**Comment by thomasgriffin** [comment]
If you need to, you can just use this to see all the data that is passed back to you: `console.log(media_attachment);`
